# Site settings
title: matematika.net
description: We are trying to study and find materials about mathematics, statistics, machine learning, deep learing, BigData
keywords: Math, Mathematics, Statistics, Probability, Development, Data Analysis, Machine Learning, Deep Learning, BigData, Hadoop, Spark, Kafka, BlockChain, IoT

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://matematika.net' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
